version: "3"


services:
  web:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: goblog
    container_name: goblog
    volumes:
      - ./config/:/config/
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    restart: always
    command:
      - ./server
    networks:
      - mynet
  db:
    image: mysql
    container_name: goblog-db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=goblog
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
