httpserver:
  host: 0.0.0.0
  port: 8080

mysql:
  url : 150.158.52.112:3306
  database: "goblog"
  params: "?charset=utf8&parseTime=true"
  user : "root"
  password : "123456"
  update: false

redis:
  host: 150.158.52.112
  port: 6379

jwt:
  secret: "goblog"
  expires: 86400